# Generated by Django 2.1.5 on 2020-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_num',
            field=models.IntegerField(),
        ),
    ]
