# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0002_auto_20200705_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
